# Generated by Django 3.2.4 on 2021-06-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('request_last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=128)),
                ('request_text', models.TextField()),
                ('reactions', models.CharField(max_length=256)),
                ('decision_time', models.FloatField()),
                ('dec_in_time', models.PositiveIntegerField()),
                ('reactions_count', models.PositiveIntegerField()),
                ('reactions_in_time_count', models.PositiveIntegerField()),
                ('reactions_average', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='kpiapp.company')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='kpiapp.specialist')),
            ],
        ),
    ]
